### ISSUE TITLE
Lifecycle Policy and Versioning optional

### ISSUE THREAD

**Issue by 35blaze** [zoitech/terraform-aws-saml#1]
Hello,
right now the module forces you to use lifecycle policies and versioning.
Can you do it, so you can opt-out - or optional.
Thanks.

**Comment by derBroBro** [comment]
Hello @35blaze ,

can you describe a littlebit more what you mean?

Malte

**Comment by 35blaze** [comment]
Hey Malte,
sry I put it in the wrong Repo
I already spoke to Geartrixy
