### ISSUE TITLE
role variables got removed?

### ISSUE THREAD

**Issue by rismoney** [zoitech/terraform-aws-saml#15]
https://github.com/zoitech/terraform-aws-saml/commit/c5ad8acbddd63cc1a254d6f702eff37a47c54104

logic/documentation no longer match.

Looks like something in PR10 didn't get merged properly.

**Comment by derBroBro** [comment]
Thank you for reporting. We will have a look.

**Comment by Geartrixy** [comment]
Hi @rismoney ,

could you be more specific? Where is the mismatch?

Thanks

**Comment by rismoney** [comment]
create_logging_role
create_billing_role

these 2 variables were somehow removed from variables.tf

https://github.com/zoitech/terraform-aws-saml#billing-and-logging-roles

**Comment by shmick** [comment]
I've submitted https://github.com/zoitech/terraform-aws-saml/pull/16 to fix this
